### ISSUE TITLE
how abt the mini map

### ISSUE THREAD

**Issue by SAV-404** [Agarian/agarian.github.io#3]
Map borders on v72 client?

**Comment by Agarian** [comment]
That option is already in my client dude...

**EDIT:** I see what you mean, since you have a v72 client of your own (pretty cool). I'm absolutely unsure where to start, mainly due to the fact that the code is compressed/simplified, so I really have no reference to old functions or variables from older clients. So I will look into this, but don't get triggered if  I can't do it lol

**Comment by SAV-404** [comment]
i actually was trying with this code which it didn't work..i don't know why 

var drawBorders = true;
function startScript() {
    handleDrawing();
}



function handleDrawing() {
 window.v72.beforeDraw = function() {
   try {
       draw();
   } catch(e) {}
 };
}
function draw() {
    minX = window.v72.dimensions[0];
    minY = window.v72.dimensions[1];
    maxX = window.v72.dimensions[2];
    maxY = window.v72.dimensions[3];
    if (drawBorders == true) {
        ctx.save();
        ctx.strokeStyle = "#000";
        ctx.lineWidth = 20;
        ctx.beginPath();
        ctx.moveTo(minX, minY);
        ctx.lineTo(maxX, minY);
        ctx.lineTo(maxX, maxY);
        ctx.lineTo(minX, maxY);
        ctx.closePath();
        ctx.stroke();
        ctx.restore();
    }
}﻿
take a look on the game code if you need to : https://github.com/SAV-404/V72-Client/blob/master/html/agar.io.js

**Comment by Agarian** [comment]
I know what hex color codes are, though I'm on mobile, so I can't really look into the code right this instant.

**Comment by SAV-404** [comment]
you can take your time Mr.Agarian .

**Comment by Agarian** [comment]
**Here's what I've found:**
- The handle drawing function at the top is not needed, as the border drawing can be a function on it's own.
- The vars `minX, minY, maxX, maxY` are non existant, or just lost in the simplified code.
- Using `window.v72.dimensions` is nowhere near the correct way to add this in.
- I'm not familiar with `window.v72.beforeDraw`, so I'm not sure what that does.
- `drawBorders` should be changeable by a checkbox/option, easy enough to implement.
- The `draw()` function should be in a function that renders all that appears on the screen (still need to find it).
- Funny bug with the stats menu, it appears at the top left corner of the screen instead of centered.

**Comment by Agarian** [comment]
At this point, I've managed to find all the old functions and vars from the old client, yet I still can't get this feature to work, I don't have high hopes for it too be honest.

**Comment by SAV-404** [comment]
-The `minX, minY, maxX, maxY` vars are in the game code,look:  `window.v72.dimensions= [-7071.067811865476, -7071.067811865476, 7071.067811865476, 7071.067811865476];`.
 may in the line _13_

- i agree with you about `window.v72.beforeDraw` :) .

-using if else statement are enough to make a  changeable option.

- the stats menu...,i'm really lazy to fix it ;-; .

i fixed a lot on this client( the one i have)...i made a skin's shop looks like the original game shop (not really but yea)...i was bored about the disappearance of the cell's round line so i had to make it visible even when the cell get bigger (no more disappearance)...easy stuffs like zoom/hidegrid options...but these god damned  borders won't work...i hope you could help.

# thanks for helping !!!

**Comment by Agarian** [comment]
Just know that `window.v72.dimensions` is not those vars. I have found the actual vars [here](https://github.com/SAV-404/V72-Client/blob/master/html/agar.io.js#L90)
I thought you should know, premium skins don't work on that client.

**Comment by SAV-404** [comment]
yea thanks for the information!!!...and all agario's skins are working on that Client cz of the script in [skin.js](https://github.com/SAV-404/V72-Client/blob/master/html/skin.js)

**Comment by Agarian** [comment]
I haven't gotten them to work.

**Comment by RevengePlayz** [comment]
Hey, i really need help @Agarian could you please add me on discord Revenge#5285 so we can chat there i have a few problems which im really struggling on.It would be the best if you could do this as soon as possible and if you dont have discord sign up here: https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwj8ktm95-nYAhXrK8AKHaAdASIQFggpMAA&url=https%3A%2F%2Fdiscordapp.com%2F&usg=AOvVaw2mEPm0IN1VJOrjVGlu_Eqi  
Thanks Revenge

**Comment by Agarian** [comment]
@RevengePlayz Just join https://discord.gg/TJpz8a and PM me from there.

**Comment by Agarian** [comment]
I think I'll just close this for the time being.

**Comment by SAV-404** [comment]
i think i found something interesting, these `minX, minY, maxX, maxY` are 100% useless, u were right from the beginning.
the real ones are these :  
`ob = 0, pb = 0, qb = 1E4, rb = 1E4,` [HERE](https://github.com/SAV-404/V72-Client/blob/a98dbb94c7d665908b6be9ed92d8ef00a3c7c9b6/html/agar.io.js#L1017)

that's a simple way to use the code, but it doesn't work, and ofc it will not : 
  `function drawBorders(e) {`
 ` (e.strokeStyle = "#ff0000", e.lineWidth = 20), `
 ` e.beginPath(),`
 ` e.moveTo(ob, pb), `
 ` e.lineTo(qb, pb), `
 ` e.lineTo(qb, rb), `
 ` e.lineTo(ob, rb), `
  `e.lineTo(ob, pb), `
  `e.stroke()`
  `}`
@Agarian plz help me on this!?
